# Install dependencies only when needed
FROM node:alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
# Rebuild the source code only when needed
FROM node:alpine AS builder
WORKDIR /usr/src/app
COPY . .
COPY --from=deps /usr/src/app/node_modules ./node_modules
RUN yarn build && yarn install --production --ignore-scripts --prefer-offline
# Production image, copy all the files and run next
FROM node:alpine AS runner

ARG NEXT_PUBLIC_DATAHUB_URL
ARG NEXT_PUBLIC_DATAHUB_ADMIN_SECRET
ARG NEXT_PUBLIC_DATAHUB_SUBSCRIPTIONS_URL
ARG NEXT_PUBLIC_KEYCLOAK_URL
ARG NEXT_PUBLIC_CLIENTID
ARG NEXT_PUBLIC_KEYCLOAK_REALM
ARG NEXT_PUBLIC_DAILYOS_SERVER_URL
ARG NEXT_PUBLIC_CURRENCY
ARG NEXT_PUBLIC_MAPS_API_KEY
ARG NEXT_PUBLIC_PAYMENTS_API_URL
ARG NEXT_PUBLIC_STRIPE_KEY
ARG NEXT_PUBLIC_EXPRESS_URL
ARG NEXT_PUBLIC_TEST_EXPRESS_URL
ARG NEXT_PUBLIC_TEST_DATAHUB_URL
ARG NEXT_PUBLIC_TEST_DATAHUB_ADMIN_SECRET
ARG NEXT_PUBLIC_NO_REPLY_EMAIL

WORKDIR /usr/src/app
ENV NODE_ENV production
COPY ./script.sh .
COPY .env .

ENV PATH /app/node_modules/.bin:$PATH
ENV SKIP_PREFLIGHT_CHECK true
ENV NEXT_PUBLIC_DATAHUB_URL $NEXT_PUBLIC_DATAHUB_URL
ENV NEXT_PUBLIC_DATAHUB_ADMIN_SECRET $NEXT_PUBLIC_DATAHUB_ADMIN_SECRET
ENV NEXT_PUBLIC_DATAHUB_SUBSCRIPTIONS_URL $NEXT_PUBLIC_DATAHUB_SUBSCRIPTIONS_URL
ENV NEXT_PUBLIC_CLIENTID $NEXT_PUBLIC_CLIENTID
ENV NEXT_PUBLIC_DAILYOS_SERVER_URL $NEXT_PUBLIC_DAILYOS_SERVER_URL
ENV NEXT_PUBLIC_CURRENCY $NEXT_PUBLIC_CURRENCY
ENV NEXT_PUBLIC_MAPS_API_KEY $NEXT_PUBLIC_MAPS_API_KEY
ENV NEXT_PUBLIC_PAYMENTS_API_URL $NEXT_PUBLIC_PAYMENTS_API_URL
ENV NEXT_PUBLIC_KEYCLOAK_REALM $NEXT_PUBLIC_KEYCLOAK_REALM
ENV NEXT_PUBLIC_KEYCLOAK_URL $NEXT_PUBLIC_KEYCLOAK_URL
ENV NEXT_PUBLIC_TEST_EXPRESS_URL $NEXT_PUBLIC_TEST_EXPRESS_URL
ENV NEXT_PUBLIC_TEST_DATAHUB_URL $NEXT_PUBLIC_TEST_DATAHUB_URL
ENV NEXT_PUBLIC_TEST_DATAHUB_ADMIN_SECRET $NEXT_PUBLIC_TEST_DATAHUB_ADMIN_SECRET
ENV NEXT_PUBLIC_NO_REPLY_EMAIL $NEXT_PUBLIC_NO_REPLY_EMAIL
# Add bash
RUN apk add --no-cache bash
# Make our shell script executable
RUN chmod +x script.sh
# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /usr/src/app/next.config.js ./
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/.next ./.next
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./package.json
EXPOSE 3000
# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1
CMD ["/bin/bash", "-c", "/usr/src/app/script.sh && yarn start"]
