-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "order"."cartPayment" add column "actionRequired" boolean
--  not null default 'false';
