-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "products"."inventoryProductBundleSachet" add column "updatedByApiKey" boolean
--  null default 'false';
