table:
  name: config
  schema: deviceHub
configuration:
  custom_column_names: {}
  custom_root_fields:
    delete: deleteConfigs
    delete_by_pk: deleteConfig
    insert: createConfigs
    insert_one: createConfig
    select: configs
    select_aggregate: conifgsAggregate
    select_by_pk: config
    update: updateConfigs
    update_by_pk: updateConfig
