table:
  name: smsConfig
  schema: notifications
configuration:
  custom_column_names: {}
  custom_root_fields:
    delete: deleteNotificationSmsConfigs
    delete_by_pk: deleteNotificationSmsConfig
    insert: createNotificationSmsConfigs
    insert_one: createNotificationSmsConfig
    select: notificationSmsConfigs
    select_aggregate: notificationSmsConfigsAggregate
    select_by_pk: notificationSmsConfig
    update: updateNotificationSmsConfigs
    update_by_pk: updateNotificationSmsConfig
object_relationships:
- name: type
  using:
    foreign_key_constraint_on: typeId
