table:
  name: product
  schema: products
configuration:
  custom_column_names: {}
  custom_root_fields:
    delete: deleteProducts
    delete_by_pk: deleteProduct
    insert: createProducts
    insert_one: createProduct
    select: products
    select_aggregate: productsAggregate
    select_by_pk: product
    update: updateProducts
    update_by_pk: updateProduct
object_relationships:
- name: addedByApiKeyReference
  using:
    foreign_key_constraint_on: addedByApiKey
- name: addedByUser
  using:
    foreign_key_constraint_on: addedBy
- name: updatedByApiKeyReference
  using:
    foreign_key_constraint_on: updatedByApiKey
- name: updatedByUser
  using:
    foreign_key_constraint_on: updatedBy
array_relationships:
- name: cartItems
  using:
    foreign_key_constraint_on:
      column: productId
      table:
        name: cartItem
        schema: order
- name: comboProductComponents
  using:
    manual_configuration:
      column_mapping:
        id: productId
      insertion_order: null
      remote_table:
        name: comboProductComponent
        schema: products
- name: customizableProductComponents
  using:
    foreign_key_constraint_on:
      column: productId
      table:
        name: customizableProductComponent
        schema: products
- name: experience_products
  using:
    foreign_key_constraint_on:
      column: productId
      table:
        name: experience_products
        schema: experiences
- name: productOptions
  using:
    foreign_key_constraint_on:
      column: productId
      table:
        name: productOption
        schema: products
computed_fields:
- comment: ""
  definition:
    function:
      name: defaultCartItem
      schema: products
  name: defaultCartItem
- comment: ""
  definition:
    function:
      name: defaultCartItemByLocation
      schema: products
  name: defaultCartItemByLocation
- comment: ""
  definition:
    function:
      name: productDiscountByLocation
      schema: products
  name: discountByLocation
- comment: ""
  definition:
    function:
      name: isProductValid
      schema: products
  name: isValid
- comment: ""
  definition:
    function:
      name: priceByLocation
      schema: products
  name: priceByLocation
- comment: Gives count of how many times product gets ordered
  definition:
    function:
      name: productOrderCount
      schema: products
  name: productOrderCount
insert_permissions:
- permission:
    backend_only: false
    check:
      addedByApiKeyReference:
        canAddProducts:
          _eq: true
    columns:
    - VegNonVegType
    - additionalText
    - assets
    - defaultProductOptionId
    - description
    - discount
    - importHistoryId
    - isArchived
    - isPopupAllowed
    - isPublished
    - name
    - nutritionId
    - price
    - tags
    set:
      addedByApiKey: x-hasura-Api-Key
  role: apiKeyRole
- permission:
    backend_only: false
    check:
      addedByUser:
        roles:
          role:
            apps:
              permissions:
                permission:
                  title:
                    _eq: canAddProducts
    columns:
    - additionalText
    - assets
    - defaultProductOptionId
    - description
    - discount
    - importHistoryId
    - isArchived
    - isPopupAllowed
    - isPublished
    - name
    - price
    - tags
    - type
    set:
      addedBy: x-hasura-Staff-Id
      updatedBy: x-hasura-Staff-Id
  role: locationRole
select_permissions:
- permission:
    allow_aggregations: true
    columns:
    - id
    - name
    - additionalText
    - description
    - assets
    - isPublished
    - isPopupAllowed
    - defaultProductOptionId
    - created_at
    - updated_at
    - tags
    - isArchived
    - type
    - price
    - discount
    - importHistoryId
    - addedBy
    - updatedBy
    - addedByApiKey
    - updatedByApiKey
    - VegNonVegType
    - productionOptionSelectionStatement
    - nutritionId
    computed_fields:
    - defaultCartItem
    - isValid
    - productOrderCount
    filter: {}
  role: apiKeyRole
- permission:
    allow_aggregations: true
    columns:
    - id
    - name
    - additionalText
    - description
    - assets
    - isPublished
    - isPopupAllowed
    - defaultProductOptionId
    - created_at
    - updated_at
    - tags
    - isArchived
    - type
    - price
    - discount
    - importHistoryId
    filter: {}
  role: consumer
- permission:
    allow_aggregations: true
    columns:
    - isArchived
    - isPopupAllowed
    - isPublished
    - defaultProductOptionId
    - id
    - importHistoryId
    - assets
    - tags
    - discount
    - price
    - additionalText
    - description
    - name
    - type
    - created_at
    - updated_at
    filter: {}
  role: guest-consumer
update_permissions:
- permission:
    check: null
    columns:
    - VegNonVegType
    - additionalText
    - assets
    - defaultProductOptionId
    - description
    - discount
    - importHistoryId
    - isArchived
    - isPopupAllowed
    - isPublished
    - name
    - nutritionId
    - price
    - productionOptionSelectionStatement
    - tags
    - type
    filter:
      updatedByApiKeyReference:
        canUpdateProducts:
          _eq: true
    set:
      updatedByApiKey: x-hasura-Api-Key
  role: apiKeyRole
