table:
  name: comboComponentOptions
  schema: products
object_relationships:
- name: linkedProduct
  using:
    manual_configuration:
      column_mapping:
        linkedProductId: id
      insertion_order: null
      remote_table:
        name: product
        schema: products
- name: productOption
  using:
    manual_configuration:
      column_mapping:
        productOptionId: id
      insertion_order: null
      remote_table:
        name: productOption
        schema: products
computed_fields:
- comment: ""
  definition:
    function:
      name: comboProductComponentOptionCartItem
      schema: products
  name: cartItem
select_permissions:
- permission:
    allow_aggregations: true
    columns:
    - comboComponentId
    - linkedProductId
    - productOptionId
    - price
    - discount
    - productId
    computed_fields:
    - cartItem
    filter: {}
  role: consumer
- permission:
    allow_aggregations: true
    columns:
    - comboComponentId
    - linkedProductId
    - productId
    - productOptionId
    - discount
    - price
    computed_fields:
    - cartItem
    filter: {}
  role: guest-consumer
