table:
  name: productOptionView
  schema: products
array_relationships:
- name: cartItems
  using:
    manual_configuration:
      column_mapping:
        id: productOptionId
      insertion_order: null
      remote_table:
        name: cartItem
        schema: order
