table:
  name: role
  schema: settings
configuration:
  custom_column_names: {}
  custom_root_fields:
    delete: deleteRoles
    delete_by_pk: deleteRole
    insert: insertRoles
    insert_one: insertRole
    select: roles
    select_aggregate: rolesAggregate
    select_by_pk: role
    update: updateRoles
    update_by_pk: updateRole
array_relationships:
- name: apps
  using:
    foreign_key_constraint_on:
      column: roleId
      table:
        name: role_app
        schema: settings
- name: users
  using:
    foreign_key_constraint_on:
      column: roleId
      table:
        name: user_role
        schema: settings
