table:
  name: app
  schema: settings
configuration:
  custom_column_names: {}
  custom_root_fields:
    delete: deleteApps
    delete_by_pk: deleteApp
    insert: insertApps
    insert_one: insertApp
    select: apps
    select_aggregate: appsAggregate
    select_by_pk: app
    update: updateApps
    update_by_pk: updateApp
array_relationships:
- name: permissions
  using:
    foreign_key_constraint_on:
      column: appId
      table:
        name: appPermission
        schema: settings
- name: roles
  using:
    foreign_key_constraint_on:
      column: appId
      table:
        name: role_app
        schema: settings
