table:
  name: activityLogs
  schema: settings
object_relationships:
- name: brand_customer
  using:
    manual_configuration:
      column_mapping:
        brand_customerId: id
      insertion_order: null
      remote_table:
        name: brand_customer
        schema: crm
- name: cart
  using:
    manual_configuration:
      column_mapping:
        cartId: id
      insertion_order: null
      remote_table:
        name: cart
        schema: order
- name: customer
  using:
    manual_configuration:
      column_mapping:
        keycloakId: keycloakId
      insertion_order: null
      remote_table:
        name: customer
        schema: crm
- name: subscriptionOccurence
  using:
    manual_configuration:
      column_mapping:
        subscriptionOccurenceId: id
      insertion_order: null
      remote_table:
        name: subscriptionOccurence
        schema: subscription
- name: subscriptionOccurence_customer
  using:
    manual_configuration:
      column_mapping:
        brand_customerId: brand_customerId
        keycloakId: keycloakId
        subscriptionOccurenceId: subscriptionOccurenceId
      insertion_order: null
      remote_table:
        name: subscriptionOccurence_customer
        schema: subscription
