table:
  name: station_user
  schema: settings
configuration:
  custom_column_names: {}
  custom_root_fields:
    delete: deleteStation_users
    delete_by_pk: deleteStation_user
    insert: createStation_users
    insert_one: createStation_user
    select: station_user
    select_aggregate: station_usersAggregate
    select_by_pk: station_users
    update: updateStation_users
    update_by_pk: updateStation_user
object_relationships:
- name: station
  using:
    foreign_key_constraint_on: stationId
- name: user
  using:
    foreign_key_constraint_on: userKeycloakId
