table:
  name: station_label_printer
  schema: settings
object_relationships:
- name: labelPrinter
  using:
    foreign_key_constraint_on: printNodeId
- name: station
  using:
    foreign_key_constraint_on: stationId
