table:
  name: operationConfig
  schema: settings
object_relationships:
- name: labelTemplate
  using:
    foreign_key_constraint_on: labelTemplateId
- name: packaging
  using:
    foreign_key_constraint_on: packagingId
- name: station
  using:
    foreign_key_constraint_on: stationId
computed_fields:
- comment: ""
  definition:
    function:
      name: operationConfigName
      schema: settings
  name: name
