table:
  name: role_app
  schema: settings
object_relationships:
- name: app
  using:
    foreign_key_constraint_on: appId
- name: role
  using:
    foreign_key_constraint_on: roleId
array_relationships:
- name: permissions
  using:
    foreign_key_constraint_on:
      column: role_appId
      table:
        name: role_appPermission
        schema: settings
