table:
  name: user
  schema: settings
array_relationships:
- name: assignedStations
  using:
    foreign_key_constraint_on:
      column: userKeycloakId
      table:
        name: station_user
        schema: settings
- name: bulkWorkOrders
  using:
    foreign_key_constraint_on:
      column: userId
      table:
        name: bulkWorkOrder
        schema: inventory
- name: roles
  using:
    foreign_key_constraint_on:
      column: userId
      table:
        name: user_role
        schema: settings
- name: sachetWorkOrders
  using:
    foreign_key_constraint_on:
      column: userId
      table:
        name: sachetWorkOrder
        schema: inventory
event_triggers:
- definition:
    delete:
      columns: "*"
    enable_manual: true
    update:
      columns:
      - email
  name: manageUser
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook: "{{DAILYOS_SERVER_URL}}/webhook/user"
