-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "developer"."apiKey" add column "canDeleteCarts" boolean
--  null default 'false';
